export const images = {
  splash: require('../assets/images/Splashimg.png'),
  whtsplogo: require('../assets/images/whtsplogo.png'),
  phone: require('../assets/images/phone.png'),
  uncheck: require('../assets/images/unchecked.png'),
  check: require('../assets/images/check.png'),
  back: require('../assets/images/back.png'),
  logo: require('../assets/images/Whatsapp.png'),
  logout: require('../assets/images/power.png'),
  update: require('../assets/images/updated.png'),
  account: require('../assets/images/account.png'),
  search: require('../assets/images/search.png'),
  dot: require('../assets/images/dots.png'),
  video: require('../assets/images/video.png'),
  telephone: require('../assets/images/telephone.png'),
  message: require('../assets/images/comment.png'),
  sendImg: require('../assets/images/sendmessage.png'),
  bgImg: require('../assets/images/whatsappbackground.png'),
};
